[phases.setup]
nixPkgs = ["openjdk21"]

[phases.build]
cmds = ["cd backend && ./gradlew clean build -x test"]

[start]
cmd = "cd backend && java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
