[phases.setup]
nixPkgs = ["openjdk21", "gradle"]

[phases.build]
cmds = ["gradle clean build -x test"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
